apiVersion: v1
kind: Service
metadata:
  name: <MODEL_NAME>
  labels:
    app.kubernetes.io/name: llm-init
    app.kubernetes.io/component: <MODEL_NAME>
    llm-init.io/engine: sglang
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: llm-init
    app.kubernetes.io/component: <MODEL_NAME>
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
